### ISSUE TITLE
Shorter player appears for audio file and for all videos viewed after viewing an audio file

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#1076] opened 2016-11-08 14:56 UTC
A shorter player appears for audio files. After I view an audio file in the shorter player and then click to view a video, the video then appears in the shorter player. This is an issue for Chrome and Firefox. I have not tested Safari.
<img width="864" alt="screen shot 2016-11-08 at 9 56 07 am" src="https://cloud.githubusercontent.com/assets/5992135/20103851/9ba27f8e-a599-11e6-86e3-74d023666a0d.png">

**Comment by afred** [comment] 2016-11-21 21:29
This may be a dupe of #1077... so address that one first.

**Done when**
  * VideoJS player always displays for audio files.
  * VideoJS player always displays for video files.

**Comment by jasoncorum** [comment] 2016-12-02 20:28
Walked through recreation scenario with @caseyedavis12 on live site and in my local #1077 branch. This does appear to be a duplicate, so closing this one out as well.

**Closed by jasoncorum** 2016-12-02 20:28 UTC
