### ISSUE TITLE
Pretty display of transcript

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#973] opened 2016-05-11 17:30 UTC
We want a display of the transcript like we have on OV. An example of a record with transcript is http://americanarchive.org/catalog/cpb-aacip_111-02c8693q

My thinking right now is that the SRT should be parsed on the fly and HTML generated from it. A different approach would be a bulk process to transform the SRT to some XML format, put that on S3, and then use XSL to translate that to both SRT/WebVTT and HTML

SRT parsing is needed regardless, though the way it ultimately gets used could be different.

**Comment by caseyedavis12** [comment] 2017-02-16 14:56
Duplicate of #1096, #1095, #1097

**Closed by caseyedavis12** 2017-02-16 14:56 UTC
Labels: User Experience
