### ISSUE TITLE
16:9 video playing in 4:3

### ISSUE THREAD

**Issue by cmhosale** [WGBH/AAPB2#1075] opened 2016-11-08 14:48 UTC
Video that I have encoded to be 16:9 aspect ratio is displaying for me as 4:3 in the new player. It plays in a 16:9 box in Sony Ci.

I'm in Chrome, and I also checked in Safari on the same machine.

See here for an example: http://americanarchive.org/catalog/cpb-aacip_508-4q7qn5zw1r

**Comment by afred** [comment] 2016-11-21 21:35
Closing.. duplicate of #1072

**Closed by afred** 2016-11-21 21:35 UTC
