### ISSUE TITLE
Gallery view of search results

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#1131] opened 2016-12-29 15:05 UTC
In a previous Blacklight update, we lost the Gallery view feature on the search results page. 

**waiting on:**
  - [ ] mocks

**Done when**
- [ ] We have the option to toggle between list view and gallery view on the search results page.  
- [ ] Gallery view displays images and title only.

**Comment by sroosa** [comment] 2018-10-26 19:09
Duplicate of #1424

**Closed by sroosa** 2018-10-26 19:09 UTC
Labels: Effort: high, Time Type: General AAPB - Non-overhead 156000, waiting: deliverable
