### ISSUE TITLE
Investigate AWS automatic snapshots

### ISSUE THREAD

**Issue by Muraszko-wgbh** [WGBH/AAPB2#1215] opened 2017-03-17 13:36 UTC
If it makes sense for AAPB, implement.

**Comment by jasoncorum** [comment] 2017-04-04 14:56
For reference: http://docs.aws.amazon.com/AmazonCloudWatch/latest/events/TakeScheduledSnapshot.html

**Comment by afred** [comment] 2017-04-13 19:34
closing, effectively a dupe of #1216.

**Closed by afred** 2017-04-13 19:34 UTC
