### ISSUE TITLE
About page floating nav

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#712] opened 2015-09-15 18:54 UTC
grab from mike's branch, or do it yourself.

**Comment by caseyedavis12** [comment] 2015-10-28 13:57
@mccalluc: adding this to the post launch QA. The About Page floating nav is still outstanding.

**Comment by caseyedavis12** [comment] 2015-11-09 18:49
@mccalluc: will you be able to resolve this without @hammicakes as part of the post launch qa?

**Comment by afred** [comment] 2015-11-10 18:00
do we know what it is supposed to look like?

**Comment by caseyedavis12** [comment] 2015-11-10 18:09
@afred: nope, I've never seen it. I thought it was supposed just allow the About menu to float down the left side as the user scrolls down an About page on Desktop.

**Comment by afred** [comment] 2015-11-10 21:16
@caseyedavis12 this more complicated than originally thought. How much of a priority is it?

**Comment by caseyedavis12** [comment] 2015-11-10 21:28
@afred low priority
________________________________

**Comment by afred** [comment] 2015-11-11 00:01
@caseyedavis12 Ok. Can we take it out of the milestone then?

**Detailed description** of why this is hard, for documentation.
  * The sidebar is contained within one of bootstrap's responsive column classes, `col-md-4`.
  * When you apply the style `position: fixed;`

**Comment by mccalluc** [comment] 2016-04-11 14:41
I'll take a look at this: Maybe fresh eyes will help.

**Comment by caseyedavis12** [comment] 2016-05-05 14:17
@mccalluc @afred: the new floating navigation on the About Menu and Participating Organizations is not working. I know that Chuck mentioned this, but I thought he was working on fixing or was going to regress that functionality. If it cannot be fixed for the redeploy, I would like to regress to the former state.

**Comment by afred** [comment] 2016-05-05 14:40
@caseyedavis12 can you come by and show which sticky nav you're talking about. The PR referenced above is working as intended, as is the sticky nav on the home page. Maybe we have different expectations here?

**Comment by afred** [comment] 2016-08-16 17:30
@caseyedavis12 I think this is fixed, confirm?

**Comment by caseyedavis12** [comment] 2016-08-16 17:31
@afred: we implemented it and did not like it so we removed it. You can close this ticket.


.

**Comment by afred** [comment] 2016-08-16 17:32
Tried it. Didn't like it. Removed it.

**Closed by afred** 2016-08-16 17:32 UTC
Labels: wont fix
