### ISSUE TITLE
Floating Navigation on homepage 

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#611] opened 2015-08-12 14:43 UTC
@Hammicakes: we have deployed the floating navigation to demo.americanarchive.org.

When I first come to the website, the floating navigation works great. But if I go to another page on the website and then come back to the homepage, the floating navigation does not appear.

**Comment by mccalluc** [comment] 2015-08-12 16:06
Confirmed: It only seems to be if you click through on the header logo: If I then reload, it starts floating again. Assigning to @Hammicakes in case this is intentional?

**Comment by Hammicakes** [comment] 2015-08-12 17:20
will look at this asap.

**Comment by Hammicakes** [comment] 2015-08-17 13:22
Question for Chuck and Drew...

When I pace the jQuery directly on the page the javascript works every time. Any suggestions?

This also effects the floating sidebar navigation requested for the About section.

**Comment by mccalluc** [comment] 2015-08-17 13:32
That's a good lead, but I'm still a bit baffled. Maybe something about the order of JS execution is clobbering the version we need? Could you either send me a diff of the edit you've made ("jQuery directly on the page"), or just commit and push it, so I can be sure I'm looking at the same thing as you? Thanks!

**Comment by mccalluc** [comment] 2015-08-17 14:30
ok, turned on the JS debugger, and when it doesn't work, affix.js just isn't being run: a breakpoint even on `+function ($) {` isn't being hit.... but the file still is being loaded? That one can happen without the other confuses me. I'll keep looking at this.

**Comment by mccalluc** [comment] 2015-08-17 15:36
Drew and I are both confused by this.
- Breakpoints on the src-ed JS just aren't being hit when you click through... but "jQuery" is being defined, as is "$.fn.affix" so something must be running?
- It is just the homepage: other page's JS still works with referer.
- Inline JS runs, just not the src-ed stuff.
- As far as I can tell, not related to bfcache: Inline JS is executed, and onpageshow is not triggered.

Experiments:
- Try coming from outside links.
- Try other debuggers... Maybe it's a firebug issue?
- Regress the code: Has it always behaved this way? At the limit, does vanilla blacklight behave the same way?

**Comment by mccalluc** [comment] 2015-09-15 18:53
Talked with Casey: grab code from Mike's branch and just make it work. Hopefully.

**Comment by caseyedavis12** [comment] 2015-11-09 18:50
@mccalluc: will you be able to resolve this without @hammicakes for the post-launch QA?

**Comment by afred** [comment] 2015-11-10 17:06
@mccalluc this bug is because the callback passed to `window.on('load', ...)` is not getting fired when you follow a link back to the home page. However it _does_ get loaded when you do a hard refresh while on the home page.

**to reproduce**
  1. go to the home page and scroll down. The affixed nav works.
  1. scroll back to the top and simply click on the main logo again.
  1. then scroll down again. The affixed nav does not work.

i will try to find a better event with which to activate the `Affix` plugin.

**Comment by afred** [comment] 2015-11-10 17:25
@mccalluc blerg... looks like it may actually be a problem with Rails' turbolinks. Trying out the `jquery-turbolinks` gem. Standby.

**Closed** 2015-11-11 15:30 UTC
